    document.getElementById('availability').insertAdjacentHTML('beforebegin',`<section class="section travel-guide" id="travel-guide"><div class="wrap"><div class="travel-guide-card"><div class="travel-guide-copy"><div class="eyebrow" data-ja="京都観光案内" data-en="Kyoto travel guide">京都観光案内</div><h2 class="section-title" data-ja="京都をめぐる" data-en="Explore Kyoto">京都をめぐる</h2><p class="lead" data-ja="宿で過ごす静かな時間とともに、京都のまち歩きもお楽しみください。季節の行事や観光スポット、交通情報は、京都市公式観光ガイドでご覧いただけます。" data-en="Alongside quiet moments at the house, discover Kyoto at your own pace. Find seasonal events, places to visit and travel information in the Kyoto City Official Guide.">宿で過ごす静かな時間とともに、京都のまち歩きもお楽しみください。季節の行事や観光スポット、交通情報は、京都市公式観光ガイドでご覧いただけます。</p></div><div class="travel-guide-action"><a class="travel-guide-link" href="https://ja.kyoto.travel/" data-href-ja="https://ja.kyoto.travel/" data-href-en="https://kyoto.travel/en/" target="_blank" rel="noopener"><span><span data-ja="京都市公式観光ガイドを見る" data-en="Explore the Kyoto City Official Guide">京都市公式観光ガイドを見る</span><small data-ja="Kyoto Travel Guide" data-en="Official travel information">Kyoto Travel Guide</small></span><b aria-hidden="true">→</b></a></div></div></div></section>`);
    let currentLang='ja';
    function setLanguage(lang){currentLang=lang;document.documentElement.lang=lang;document.querySelectorAll('[data-ja][data-en]').forEach(el=>{el.innerHTML=el.dataset[lang]});document.querySelectorAll('[data-placeholder-ja]').forEach(el=>{el.placeholder=el.dataset['placeholder'+(lang==='ja'?'Ja':'En')]});document.querySelectorAll('[data-aria-ja]').forEach(el=>{el.setAttribute('aria-label',el.dataset['aria'+(lang==='ja'?'Ja':'En')])});document.querySelectorAll('[data-href-ja]').forEach(el=>{el.href=el.dataset['href'+(lang==='ja'?'Ja':'En')]});document.querySelectorAll('[data-lang]').forEach(btn=>btn.setAttribute('aria-pressed',String(btn.dataset.lang===lang)));document.title=lang==='ja'?'KINO SPACE KYOTO | 京都・紫野の一棟貸し宿':'KINO SPACE KYOTO | Private Stay in Kyoto';document.querySelector('meta[name="description"]').content=lang==='ja'?'京都市北区・紫野の一棟貸し宿 KINO SPACE KYOTO。最大5名、230㎡。北野天満宮まで徒歩約6分。':'KINO SPACE KYOTO is a 230 m² private stay in Murasakino, Kyoto, for up to five guests, about 6 minutes on foot from Kitano Tenmangu Shrine.';localStorage.setItem('kino-language',lang)}
    const savedLang=localStorage.getItem('kino-language');setLanguage(savedLang||(navigator.language.toLowerCase().startsWith('ja')?'ja':'en'));document.querySelectorAll('[data-lang]').forEach(btn=>btn.addEventListener('click',()=>setLanguage(btn.dataset.lang)));
    const header=document.getElementById('header');addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>30));
    const menu=document.getElementById('menu'),links=document.getElementById('navlinks');menu.addEventListener('click',()=>links.classList.toggle('open'));links.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>links.classList.remove('open')));
    const today=new Date();today.setMinutes(today.getMinutes()-today.getTimezoneOffset());const min=today.toISOString().split('T')[0];document.getElementById('checkin').min=min;document.getElementById('checkout').min=min;
    document.getElementById('checkin').addEventListener('change',e=>{const out=document.getElementById('checkout');out.min=e.target.value;if(out.value&&out.value<=e.target.value)out.value=''});
    document.getElementById('bookingForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(f.get('checkout')<=f.get('checkin')){alert(currentLang==='ja'?'チェックアウト日はチェックイン日より後の日付を選んでください。':'Please select a check-out date after your check-in date.');return}const guests=document.getElementById('guests').selectedOptions[0].textContent;const body=currentLang==='ja'?`KINO SPACE KYOTO 予約希望\n\nお名前：${f.get('name')}\nメール：${f.get('email')}\nチェックイン：${f.get('checkin')}\nチェックアウト：${f.get('checkout')}\n人数：${guests}\n\nご要望・到着予定時刻：\n${f.get('message')||'なし'}\n\n※空室、確定料金、クレジットカード決済方法のご案内をお願いします。`:`KINO SPACE KYOTO — Reservation Request\n\nName: ${f.get('name')}\nEmail: ${f.get('email')}\nCheck-in: ${f.get('checkin')}\nCheck-out: ${f.get('checkout')}\nGuests: ${guests}\n\nRequests and estimated arrival time:\n${f.get('message')||'None'}\n\nPlease confirm availability, the final rate and credit card payment instructions.`;document.getElementById('success').classList.add('show');const subject=currentLang==='ja'?`【KINO SPACE KYOTO予約希望】${f.get('name')}様`:`KINO SPACE KYOTO reservation request — ${f.get('name')}`;location.href=`mailto:kinospacekyoto@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`});
